Update git-rebase-main to infer the origin branch

diff --git a/git/bin/git-rebase-main b/git/bin/git-rebase-main
--- a/git/bin/git-rebase-main
+++ b/git/bin/git-rebase-main
@@ -3,12 +3,23 @@
 set -e
 
 git_prefix="[git]:"
-destination=${1:-main}
+destination=$1
 branch=$(git rev-parse --abbrev-ref HEAD)
 
 _echo() {
   echo -e "$git_prefix $@"
 }
+
+if [ -z "$destination" ]; then
+  if $(git branch-check main); then
+    destination="main"
+  elif $(git branch-check master); then
+    destination="master"
+  else
+    echo "couldn't infer destination branch. main and master not here. exiting..."
+    exit 1
+  fi
+fi
 
 _echo "fetching origin/$destination..."
 git fetch origin $destination
